name: Web CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Chrome for Lighthouse
      - name: Setup Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1

      # Install project deps (Playwright, http-server, LHCI CLI are in package.json)
      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps

      # UI tests (Playwright starts/stops a local server from playwright.config.js)
      - name: Run Playwright tests
        run: npm test

      # Lighthouse CI against local server defined in .lighthouserc.json
      - name: Run Lighthouse CI
        env:
          LHCI_CHROMIUM_PATH: ${{ steps.chrome.outputs.chrome-path }}
        run: |
          npx lhci autorun \
            --config=.lighthouserc.json \
            --collect.settings.chromeFlags="--no-sandbox" \
            --upload.target=temporary-public-storage

      # Artifacts
      - name: Upload Lighthouse artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci
          if-no-files-found: warn

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
