name: Web CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Ensure Chrome is available for Lighthouse
      - uses: browser-actions/setup-chrome@v1

      # Install deps
      - run: npm install
      - run: npx playwright install --with-deps

      # Run Playwright UI tests (starts http-server via config)
      - run: npm test

      # Run Lighthouse CI against the local server and publish a public report link
      - name: Run Lighthouse CI
        run: |
          npx lhci autorun \
            --config=.lighthouserc.json \
            --upload.target=temporary-public-storage

      # Always upload artifacts, even if a step warns/fails
      - name: Upload Lighthouse artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci
          if-no-files-found: warn

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
